account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from account.views import custom_login, profile, RegisterView

app_name = "account"

urlpatterns = [
    # path("login/", AccountLoginView.as_view(), name="login"),
    path("login/", custom_login, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile, name="profile"),
    path("register/", RegisterView.as_view(), name="register")
]

book_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/urls.py
from django.urls import path

from books.views import BooksListView, BookDetailView, HomeView, SearchView, search

urlpatterns = [
    path('', HomeView.as_view(), name="homepage"),
    path('books/', BooksListView.as_view(), name="books_list"),
    path('books/<int:pk>/', BookDetailView.as_view(), name="book_detail"),
    path('search/', search, name="search")
]

account/models.py
from django.db import models

# Create your models here.

books/models.py
from django.conf import settings
from django.db import models


class Book(models.Model):
    class LanguageTypes(models.TextChoices):
        UZBEK = 'uzbek', 'Uzbek'
        RUSSIAN = 'russian', 'Russian'
        ENGLISH = 'english', 'English'

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.FloatField()
    sale_percent = models.PositiveSmallIntegerField(default=0)
    best_seller = models.BooleanField(default=False)
    pub_year = models.PositiveIntegerField(null=True)
    page_size = models.PositiveIntegerField()
    lang = models.CharField(max_length=50, choices=LanguageTypes.choices)
    file = models.FileField()
    image = models.ImageField()
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="books")
    author = models.ForeignKey("Author", on_delete=models.CASCADE, related_name="books")


class Category(models.Model):
    name = models.CharField(max_length=100)


class Author(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

account/forms.py
from django import forms
from django.contrib.auth.forms import UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class CustomAuthenticationForm(forms.Form):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

account/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView

from account.forms import CustomAuthenticationForm, UserRegistrationForm


class AccountLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = "account/login.html"


def custom_login(request):
    form = CustomAuthenticationForm(request.POST or None)
    if form.is_valid():
        username = request.POST.get("username")
        password = request.POST.get("password")
        if username is not None and password:
            user = authenticate(
                request, username=username, password=password
            )
            login(request, user)
            return redirect("account:profile")
    return render(request, "account/login.html", {"form": form})


@login_required
def profile(request):
    return render(request, "account/profile.html", {"user": request.user})


class RegisterView(FormView):
    template_name = 'account/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy("account:login")

books/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from books.models import Book


class HomeView(ListView):
    queryset = Book.objects.order_by("-id")
    template_name = "home.html"
    context_object_name = "books"


class BaseView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context


class HomeView(ListView):
    queryset = Book.objects.order_by("-id")
    template_name = "home.html"
    context_object_name = "books"


class BooksListView(ListView):
    queryset = Book.objects.order_by("-id")
    template_name = "books/books.html"
    context_object_name = "books"


class BookDetailView(DetailView):
    queryset = Book.objects.all()
    template_name = "books/book_detail.html"
    context_object_name = "book"


class SearchView(ListView):
    queryset = Book.objects.all()
    template_name = "search.html"
    context_object_name = "results"


def search(request):
    search_query = request.POST.get("search")
    expression = (
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query)
    )
    queryset = Book.objects.filter(expression)
    return render(request, "search.html", {"results": queryset})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage' %}">Book store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'books_list' %}">Books</a>
                </li>
            </ul>
            <form class="d-flex" role="search" action="{% url 'search' %}" method="post">
                {% csrf_token %}
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:profile' %}">
                            <button type="button" class="btn btn-success">Profile</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">
                            <button type="button" class="btn btn-primary">Logout</button>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">
                            <button type="button" class="btn btn-success">Login</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:register' %}">
                            <button type="button" class="btn btn-primary">Register</button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

templates/books/book_detail.html
{% extends 'base.html' %}


{% block content %}

    <div class="container mt-5 mb-3">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ book.image.url }}" alt="Product Image" class="img-fluid">
            </div>
            <div class="col-md-6">
                <h2>{{ book.title }}</h2>
                <p>{{ book.description }}</p>
                <p><b>Author:</b> {{ book.author.name }}</p>
                <p><b>Publication:</b> {{ book.pub_year }}</p>
                <p><b>Publication date:</b> {{ book.page_size }}</p>
                <p><b>Language:</b> {{ book.lang }}</p>
                <h3>Price: {{ book.price }}</h3>
                <button class="btn btn-primary">Add to Cart</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/books/books.html
{% extends 'base.html' %}

{% block title %}
    HomePage
{% endblock %}

{% block content %}
    <div class="container custom-home">
        <div class="row">
            {% for book in books %}
                <div class="col-md-4 card border">
                    <div class="card border mb-4 box-shadow h-50">
                        <img class="card-img-top" src="{{ book.image.url }}" alt="Bu Yerda Rasm Bor!">
                        <div class="card-body">
                            <h5 class="card-title custom-title">
                                <a href="{% url 'book_detail' book.id %}">{{ book.title }}</a>
                            </h5>
                            {% if book.description|length > 80 %}
                                <p class="card-text">{{ book.description|slice:80 }}</p>
                            {% else %}
                                <p class="card-text">{{ book.description }}</p>
                            {% endif %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'book_detail' book.id %}" class="btn btn-sm btn-outline-secondary">
                                        More
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card-group">
            {% for book in books %}
                <div class="card">
                    <img src="{{ book.image.url }}" class="card-img-top" alt="..." width="100" height="500">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        {% if book.descreption|length > 80 %}
                        <p class="card-text">{{ book.desc }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-body-secondary">{{ book.pub_year }}</small>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}
    Search
{% endblock %}

{% block content %}
    <div class="container custom-home">
        <div class="row">
            {% for book in results %}
                <div class="col-md-4 card border">
                    <div class="card border mb-4 box-shadow h-50">
                        <img class="card-img-top" src="{{ book.image.url }}" alt="Bu Yerda Rasm Bor!">
                        <div class="card-body">
                            <h5 class="card-title custom-title">
                                <a href="{% url 'book_detail' book.id %}">{{ book.title }}</a>
                            </h5>
                            {% if book.description|length > 80 %}
                                <p class="card-text">{{ book.description|slice:80 }}</p>
                            {% else %}
                                <p class="card-text">{{ book.description }}</p>
                            {% endif %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'book_detail' book.id %}" class="btn btn-sm btn-outline-secondary">
                                        More
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}